- name: 升级centos7内核
  hosts: k8s
  become: true
  tasks:
    - name: 修改hostname
      copy:
        dest: /etc/hostname
        content: '{{ inventory_hostname }}'

    - name: 分发hosts
      copy:
        src: /etc/hosts
        dest: /etc/hosts

    - name: 删除自带yum源
      file:
        path: /etc/yum.repos.d/CentOS7-Base-Wangsu.repo
        state: absent

    - name: 分发aliyun-centos7的yum源
      copy:
        src: /etc/yum.repos.d/CentOS-Base.repo
        dest: /etc/yum.repos.d/CentOS-Base.repo
        mode: '0644'

    - name: 清理yum过期缓存并建立新缓存
      shell: yum clean all
    
    - name: no   
      shell: yum makecache

    - name: init
      yum:
        name: epel-release

    - name: update all
      yum:
        name: "*"
        state: latest
      ignore_errors: true

    - name: 下载内核rpm安装包
      get_url: 
        url: https://dl.lamp.sh/kernel/el7/kernel-ml-6.7.2-1.el7.elrepo.x86_64.rpm
        dest: /tmp/kernel-ml-6.7.2-1.el7.elrepo.x86_64.rpm

    - name: 下载内核rpm-devel安装包
      get_url: 
        url: https://dl.lamp.sh/kernel/el7/kernel-ml-devel-6.7.2-1.el7.elrepo.x86_64.rpm
        dest: /tmp/kernel-ml-devel-6.7.2-1.el7.elrepo.x86_64.rpm

    - name: 安装内核
      command: yum localinstall -y /tmp/kernel-ml-6.7.2-1.el7.elrepo.x86_64.rpm /tmp/kernel-ml-devel-6.7.2-1.el7.elrepo.x86_64.rpm
      register: rpm_output
    
    - name: 获取目前内核可用版本
      command: awk -F\' '$1=="menuentry " {print  $2}' /etc/grub2.cfg
      register: kernel_info

    - name: 修改内核启动版本
      command: grub2-set-default 0
      register: start
 
    - name: 获取当前生效的内核信息
      command: grub2-editenv list
      register: envlist

    - name: 重启服务器
      shell: reboot
