- name: 安装和配置 Containerd
  hosts: k8s
  tasks:
    - name: 添加 Docker CE 源（用于安装 containerd）
      yum_repository:
        name: docker-ce
        description: Docker CE
        baseurl: https://mirrors.aliyun.com/docker-ce/linux/centos/7.9/x86_64/stable
        gpgcheck: no
        enabled: yes

    - name: 安装 containerd
      yum:
        name:
          - containerd.io
        state: present
    - name: 生成 containerd 配置文件
      shell:
        containerd config default > /etc/containerd/config.toml
    
    - name: 配置 containerd 
      replace:
        path=/etc/containerd/config.toml
        regexp="SystemdCgroup = false"
        replace="SystemdCgroup = true"
    
    - name: 修改 containerd 默认sanbox镜像
      replace:
        path=/etc/containerd/config.toml
        regexp="registry.k8s.io/pause:3.6"
        replace="registry.aliyuncs.com/google_containers/pause:3.10"
    
    - name: 重启 containerd
      systemd:
        name: containerd
        state: restarted
        enabled: yes
