- name: k8s lb init
  hosts: no
  become: true
  tasks:
    #- name: 禁止swap空间
    #  shell: |
    #    swapoff -a

    #- name: 取消fstab开机启动
    #  lineinfile:
    #    path: /etc/fstab
    #    regexp: '^\s*([^#]\S+\s+\S+\s+swap\s+)'
    #    line: '# \1'
    #    state: present
    
    #- name: 删除原有yum仓库
    #  shell: rm /etc/yum.repos.d/CentOS7-Base-Wangsu.repo
    #  ignore_errors: true
    
    #- name: 添加阿里云centos7镜像yum源
    #  copy:
    #    src: /etc/yum.repos.d/CentOS-Base.repo
    #    dest: /etc/yum.repos.d/CentOS-Base.repo

    #- name: 清理yum缓存和新建缓存
    #  shell: |
    #    yum clean all
    #    yum makecache
    
    - name: 安装epel-release
      yum:
        name: 
          - epel-release
        state: latest

    - name: 安装高可用组件
      yum:
        name:
          - nginx
          - keepalived
          - nginx-mod-stream
        state: latest

    - name: 部署内核优化参数
      copy:
        content: |
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          fs.may_detach_mounts = 1
          vm.overcommit_memory=1
          vm.panic_on_oom=0
          fs.inotify.max_user_watches=89100
          fs.file-max=52706963
          fs.nr_open=52706963
          net.netfilter.nf_conntrack_max=2310720
          net.ipv4.tcp_keepalive_time = 600
          net.ipv4.tcp_keepalive_probes = 3
          net.ipv4.tcp_keepalive_intvl =15
          net.ipv4.tcp_max_tw_buckets = 36000
          net.ipv4.tcp_tw_reuse = 1
          net.ipv4.tcp_max_orphans = 327680
          net.ipv4.tcp_orphan_retries = 3
          net.ipv4.tcp_syncookies = 1
          net.ipv4.tcp_max_syn_backlog = 16384
          net.ipv4.ip_conntrack_max = 65536
          net.ipv4.tcp_max_syn_backlog = 16384
          net.ipv4.tcp_timestamps = 0
          net.core.somaxconn = 16384
        dest: /etc/sysctl.d/nginx.conf
      notify: reload sysctl

    - name: 开启nginx服务
      systemd:
        name: nginx
        #state: restarted
        enabled: true

    - name: 创建stream LB4配置文件夹
      file:
        path: /etc/nginx/stream
        state: directory
        mode: 0755

    - name: 修改默认nginx配置
      copy:
        src: /tmp/nginx.conf
        dest: /etc/nginx/default.conf
        mode: 0644
        backup: true
      notify: reload nginx

    - name: 加入四层代理配置
      copy:
        src: /tmp/k8s.conf
        dest: /etc/nginx/stream/k8s.conf
      notify: reload nginx

    - name: 加入高可用vip
      template:
        src: /tmp/keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
        backup: true
      vars:
        state: "{{ kp_state }}"
        priority: "{{ kp_priority }}"

    - name: 启动keepalived
      systemd:
        name: keepalived
        state: restarted
        enabled: true

  handlers:
    - name: reload sysctl
      command: sysctl --systema

    - name: reload nginx
      command: nginx -s reload
