- name: k8s lb init
  hosts: {{ 负载均衡节点 }}
  become: true
  tasks:
    - name: 安装epel-release
      yum:
        name: 
          - epel-release
        state: latest

    - name: 安装高可用组件
      yum:
        name:
          - nginx
          - keepalived
          - nginx-mod-stream
        state: latest

    - name: 部署内核优化参数
      copy:
        content: |
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          fs.may_detach_mounts = 1
          vm.overcommit_memory=1
          vm.panic_on_oom=0
          fs.inotify.max_user_watches=89100
          fs.file-max=52706963
          fs.nr_open=52706963
          net.netfilter.nf_conntrack_max=2310720
          net.ipv4.tcp_keepalive_time = 600
          net.ipv4.tcp_keepalive_probes = 3
          net.ipv4.tcp_keepalive_intvl =15
          net.ipv4.tcp_max_tw_buckets = 36000
          net.ipv4.tcp_tw_reuse = 1
          net.ipv4.tcp_max_orphans = 327680
          net.ipv4.tcp_orphan_retries = 3
          net.ipv4.tcp_syncookies = 1
          net.ipv4.tcp_max_syn_backlog = 16384
          net.ipv4.ip_conntrack_max = 65536
          net.ipv4.tcp_max_syn_backlog = 16384
          net.ipv4.tcp_timestamps = 0
          net.core.somaxconn = 16384
        dest: /etc/sysctl.d/nginx.conf
      notify: reload sysctl

    - name: 开启nginx服务
      systemd:
        name: nginx
        #state: restarted
        enabled: true

    - name: 加入四层代理配置
      template:
        src: /tmp/k8s.conf/j2
        dest: /etc/nginx/conf.d/k8s.conf
      notify: reload nginx

    - name: 加入高可用vip
      template:
        src: /tmp/keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
        backup: true
      vars:
        state: "{{ kp_state }}"
        priority: "{{ kp_priority }}"

    - name: 启动keepalived
      systemd:
        name: keepalived
        state: restarted
        enabled: true

  handlers:
    - name: reload sysctl
      command: sysctl --systema

    - name: reload nginx
      command: nginx -s reload
