- name: k8s lb init
  hosts: no
  become: true
  tasks:
    - name: 开启nginx服务
      systemd:
        name: nginx
        state: started
        enabled: true

    - name: 部署内核优化参数
      copy:
        content: |
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          fs.may_detach_mounts = 1
          vm.overcommit_memory=1
          vm.panic_on_oom=0
          fs.inotify.max_user_watches=89100
          fs.file-max=52706963
          fs.nr_open=52706963
          net.netfilter.nf_conntrack_max=2310720
          net.ipv4.tcp_keepalive_time = 600
          net.ipv4.tcp_keepalive_probes = 3
          net.ipv4.tcp_keepalive_intvl =15
          net.ipv4.tcp_max_tw_buckets = 36000
          net.ipv4.tcp_tw_reuse = 1
          net.ipv4.tcp_max_orphans = 327680
          net.ipv4.tcp_orphan_retries = 3
          net.ipv4.tcp_syncookies = 1
          net.ipv4.tcp_max_syn_backlog = 16384
          net.ipv4.ip_conntrack_max = 65536
          net.ipv4.tcp_max_syn_backlog = 16384
          net.ipv4.tcp_timestamps = 0
          net.core.somaxconn = 16384
        dest: /etc/sysctl.d/nginx.conf
      notify: reload sysctl
    
    - name: 加入lb_test的nginx配置
      template:
        src: /tmp/lb_test.conf.j2
        dest: /etc/nginx/conf.d/lb_test.conf
      vars:
        state: "{{ state }}"
        priority: "{{ priority }}"
      notify: reload nginx
    
    - name: 加入k8s-api的nginx高可用配置
      template:
        src: /tmp/k8s.conf.j2
        dest: /etc/nginx/conf.d/k8s.conf
  

  handlers:
    - name: reload nginx
      command: nginx -s reload

    - name: reload sysctl
      command: sysctl --system
