---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-tls-deploy-role
  namespace: default
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - secrets
    verbs:
      - get
      - delete
      - update
      - create
      - list
---
# rolebinding-kuboard.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-tls-deploy-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: k8s-tls-deploy  # 替换为你的 Service Account 名称
  namespace: default    # Service Account 所在的命名空间（假设它在default命名空间）
roleRef:
  kind: Role
  name: k8s-tls-deploy-role
  apiGroup: rbac.authorization.k8s.io
